on:
  [workflow_dispatch]

name: Apply infrastructure

jobs:
  infrastructure-dev:
    name: Dev
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
    secrets: inherit

  infrastructure-prod:
    name: Prod
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
    secrets: inherit