on:
  [workflow_dispatch]

name: Apply infrastructure

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

jobs:
  terraform-dev:
    name: 'Terraform dev'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure/environments/dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      id: init
      run: terraform init
      
    - name: Terraform apply
      id: apply
      run: terraform apply -auto-approve


  terraform-prod:
    name: 'Terraform prod'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure/environments/prod
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform apply
      id: apply
      run: terraform apply -auto-approve

  ansible-dev:
    name: Ansible dev
    needs: terraform-dev
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install ssh key
      run: |
        mkdir -p ~/.ssh/
        echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa 52.232.43.244 >> ~/.ssh/known_hosts
        ssh-keyscan -t rsa 52.178.79.182 >> ~/.ssh/known_hosts

    - name: Install ansible
      run: python3 -m pip install ansible
    
    - name: Run playbook
      run: ansible-playbook --private-key ~/.ssh/id_rsa -i inventory.yaml playbook.yaml
      working-directory: ./playbooks